# Generated by Django 4.2.23 on 2025-08-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_email_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("superuser", "SuperUser")],
                default="user",
                max_length=10,
            ),
        ),
    ]
