# Generated by Django 4.2.23 on 2025-08-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("users", "0004_remove_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="custom_groups",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="groups.group"
            ),
        ),
    ]
