# Generated by Django 4.2.23 on 2025-08-02 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_role"),
    ]

    operations = [
        migrations.RunSQL(
            # Forward: Clean up data and update foreign key to point to auth_group
            """
            -- First, clear any orphaned relationships
            DELETE FROM users_user_groups WHERE group_id NOT IN (SELECT id FROM auth_group);
            
            -- Drop old constraint only if it exists
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_user_groups_group_id_9afc8d0e_fk_groups_group_id') THEN
                    ALTER TABLE users_user_groups DROP CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_groups_group_id;
                END IF;
            END $$;
            
            -- Add new constraint pointing to auth_group only if it doesn't exist
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname LIKE '%auth_group%' AND conrelid = 'users_user_groups'::regclass) THEN
                    ALTER TABLE users_user_groups 
                    ADD CONSTRAINT users_user_groups_group_id_fk_auth_group 
                    FOREIGN KEY (group_id) REFERENCES auth_group (id) DEFERRABLE INITIALLY DEFERRED;
                END IF;
            END $$;
            """,
            # Reverse: No-op since the constraint is already correct
            """
            -- No reverse needed - constraint is already pointing to auth_group
            """,
        ),
    ]
