# Generated by Django 4.2.23 on 2025-08-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("users", "0005_user_custom_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="custom_groups",
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to.",
                related_name="user_set",
                related_query_name="user",
                to="groups.group",
                verbose_name="groups",
            ),
        ),
    ]
