# Generated by Django 4.2.23 on 2025-08-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
